---
ID: "5d3caaf2-d379-472d-b986-b2ca6914167d"
Parent: "5153aaaf-55d0-4196-8392-c2a437763d43"
Template: "5153aaaf-55d0-4196-8392-c2a437763d43"
Path: /sitecore/templates/Project/Demo/Pages/Form Page/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/window_dialog.png
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{F904F489-7129-4A77-8791-59662AB2B399}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{8AF7F6ED-C5AE-45F8-90ED-02694A861800}">
        <p
          uid="{D55FF78E-CFBA-469E-B2FA-5449935781A9}"
          key="content-body"
          md="{40C4A77F-A7CF-4F77-98E7-507F32D3B185}" />
        <p
          uid="{6A81AE14-9144-41F0-830F-7215976E38B2}"
          key="full-width-column"
          md="{3278B1F5-B1BB-4825-8E11-C5BDF38A1FEC}" />
        <p
          uid="{3EFB7F7F-05C2-4D76-B775-321E7FA93C10}"
          key="content-width-column"
          md="{9D5AE272-735F-4389-A9F8-7AE5FF143D8D}" />
        <p
          uid="{39EA2E2C-AA3E-41F4-9F1A-F8EBFEFB7636}"
          key="primary-column-left"
          md="{82F6978E-69B6-4947-A764-FCF236FEF694}" />
        <p
          uid="{4AE42688-8B77-4048-B809-F607167148CF}"
          key="secondary-column-right"
          md="{EF37F9BF-429E-4318-8887-9FB6561B3592}" />
        <p
          uid="{EB04B51C-428B-485A-ADD5-B09A97EBC357}"
          key="secondary-column-left"
          md="{36726529-98D3-4963-9176-5FD2F0939E32}" />
        <p
          uid="{D6803DC2-59E6-419C-A476-B5A12CCF74D2}"
          key="primary-column-right"
          md="{65876821-BFB5-409F-BAEE-67AF0415FA5D}" />
        <p
          uid="{CCBF74A0-4413-44EA-BBF7-5B351E9A674E}"
          key="50-50-left-column"
          md="{9C4CDE52-9837-45D3-ADCC-0D3764B57190}" />
        <p
          uid="{4B692538-C097-4191-A4CE-32D37062DE9E}"
          key="50-50-right-column"
          md="{9C4CDE52-9837-45D3-ADCC-0D3764B57190}" />
        <p
          uid="{A80B9449-FCDB-488D-9ECE-6CADE4F7F5D5}"
          key="rich-text"
          md="{6B868C5D-7043-41C1-B504-3F056AF8ADD1}" />
        <r
          ds=""
          id="{04E17BDE-B4F7-4B77-BED6-2A24F059D04D}"
          par="Caching=0%7c0%7c0%7c0%7c0%7c0%7c0%7c0&amp;Include Bottom Margin=1"
          ph="content-body"
          uid="{708B05EC-AF57-41CF-B17D-35052ED6FBEC}" />
        <r
          id="{60C2AC1C-4754-4914-B11A-37F0DF825B43}"
          ph="content-body"
          uid="{17AFC2CC-A480-45BB-B734-3F7A9AFD5037}" />
        <r
          id="{4FC58D75-BE0A-469A-88A8-D5678805B423}"
          ph="/content-body/content-width-column-{17AFC2CC-A480-45BB-B734-3F7A9AFD5037}-0"
          uid="{48B61B1C-1028-45D6-853B-880F71751CB2}" />
        <r
          ds=""
          id="{089971A7-90DA-4923-8712-BE61C59DD237}"
          par=""
          ph="/content-body/content-width-column-{17AFC2CC-A480-45BB-B734-3F7A9AFD5037}-0"
          uid="{1499620E-F13E-40BD-A280-BD8B192F2FBB}" />
        <r
          id="{6F3D1130-74EC-4C8B-B8A7-8BD1D51B17E7}"
          ph="content-body"
          uid="{332EBDE1-D7DE-456B-8835-80ED4E50B670}" />
        <r
          id="{3E615E7F-8DB2-4648-B7E1-E9C2F05FFD08}"
          ph="content-body"
          uid="{33D47014-5558-4DAB-8647-D25B2B7F2F77}" />
        <r
          id="{1B8B6412-BC11-4D18-8547-28380C1BCCF7}"
          ph="content-body"
          uid="{49ABABA1-A0D8-40E4-A94C-5DC76A6C48C2}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190506T151048Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
