---
ID: "c8133985-0a25-4bbe-9b12-50887c350448"
Parent: "edeb2c49-9782-4516-a356-5ab0c099759c"
Template: "edeb2c49-9782-4516-a356-5ab0c099759c"
Path: /sitecore/templates/Project/Atrius/Pages/Event Detail Page/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/document_pinned.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {EB9DA56D-99FE-4AEB-8919-97AE4B416DA7}
    {FCD3BD0D-71BD-45F7-A758-6ABABCF3F0F6}
    {A87A00B1-E6DB-45AB-8B54-636FEC3B5523}
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{F904F489-7129-4A77-8791-59662AB2B399}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{A2DE3965-E340-45B4-9FAB-3F35BECE08C1}">
        <p
          uid="{9D4C7049-8BC4-4F38-8FA6-9AEF13DB4F20}"
          key="content-body"
          md="/sitecore/layout/Placeholder Settings/Project/Atrius/Event Detail Page/Base/Body" />
        <p
          uid="{9EC583C8-0EFC-4115-9228-4C28E8FB1D45}"
          key="50-50-left-column"
          md="/sitecore/layout/Placeholder Settings/Project/Atrius/Event Detail Page/Containers/50 Percent Column" />
        <p
          uid="{9D389A07-6C23-48A1-9CAC-AAA23CE1D2CF}"
          key="50-50-right-column"
          md="/sitecore/layout/Placeholder Settings/Project/Atrius/Event Detail Page/Containers/50 Percent Column" />
        <p
          uid="{476B8789-49CF-4343-9D4F-10E576B90018}"
          key="content-width-column"
          md="/sitecore/layout/Placeholder Settings/Project/Atrius/Event Detail Page/Containers/Full Width Content" />
        <p
          uid="{98E519C5-B0F5-40E5-89AD-CE89377910DF}"
          key="secondary-column-left"
          md="/sitecore/layout/Placeholder Settings/Project/Atrius/Event Detail Page/Containers/30 Percent Left Column" />
        <p
          uid="{93731C05-726F-4672-83CC-9990AFC00BA3}"
          key="secondary-column-right"
          md="/sitecore/layout/Placeholder Settings/Project/Atrius/Event Detail Page/Containers/30 Percent Right Column" />
        <p
          uid="{DE7D578A-38DF-407E-B5B6-3531011CE460}"
          key="primary-column-left"
          md="/sitecore/layout/Placeholder Settings/Project/Atrius/Event Detail Page/Containers/70 Percent Left Column" />
        <p
          uid="{BDC82F61-E3DD-43C0-8FD3-07C52EB5515B}"
          key="primary-column-right"
          md="/sitecore/layout/Placeholder Settings/Project/Atrius/Event Detail Page/Containers/70 Percent Right Column" />
        <p
          uid="{67A2E176-2936-4F9E-95A9-CB42AA21F53C}"
          key="rich-text"
          md="/sitecore/layout/Placeholder Settings/Project/Atrius/Event Detail Page/Rich Text/Rich Text" />
        <r
          ds=""
          id="{60C2AC1C-4754-4914-B11A-37F0DF825B43}"
          par="Include Bottom Margin=1"
          ph="content-body"
          uid="{1EBFBEC1-4F1B-4524-B33A-C059D586DAD4}" />
        <r
          ds=""
          id="{FC3D7B61-8FFE-4FA5-8E62-841A0E8A8F17}"
          par=""
          ph="/content-body/content-width-column-{1EBFBEC1-4F1B-4524-B33A-C059D586DAD4}-0"
          uid="{56EB500D-BF13-47AE-BA65-0F1FBD7E0BB9}" />
        <r
          ds=""
          id="{4FC58D75-BE0A-469A-88A8-D5678805B423}"
          par=""
          ph="/content-body/content-width-column-{1EBFBEC1-4F1B-4524-B33A-C059D586DAD4}-0"
          uid="{9DF76156-173D-411E-8872-A5C3334C13C2}" />
        <r
          id="{6F3D1130-74EC-4C8B-B8A7-8BD1D51B17E7}"
          ph="content-body"
          uid="{335CD150-84A4-49C4-8BD2-693ECA039674}" />
        <r
          ds=""
          id="{089971A7-90DA-4923-8712-BE61C59DD237}"
          par=""
          ph="/content-body/primary-column-left-{335CD150-84A4-49C4-8BD2-693ECA039674}-0"
          uid="{2B292640-87CF-49D0-AE7E-9C57E3E3B5CF}" />
        <r
          ds=""
          id="{A7AF7451-052E-4EE1-AF11-DD154667963E}"
          par=""
          ph="/content-body/primary-column-left-{335CD150-84A4-49C4-8BD2-693ECA039674}-0"
          uid="{B301451E-36B3-4128-90BF-085245633E0B}" />
        <r
          ds=""
          id="{FE4B1631-281C-4567-8A1C-5FEE6E538364}"
          par=""
          ph="/content-body/secondary-column-right-{335CD150-84A4-49C4-8BD2-693ECA039674}-0"
          uid="{80C6C08D-5E73-4C5B-A789-7C906767CE23}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160223T222401Z
    - ID: "4037909f-26bb-42b7-9f37-7cd0b5e941bb"
      Hint: Start Date
      Value: $now
    - ID: "d7b9c27c-79e3-42a7-9b46-bff652ef0981"
      Hint: Content Type
      Value: "{2B491ED7-BA51-451E-B36B-909D4F68F02C}"
