---
ID: "c69d244b-4c1a-411a-96f0-6657bc894a1c"
Parent: "ce166101-2f7f-4fcd-a95c-1bf48fb682cb"
Template: "ce166101-2f7f-4fcd-a95c-1bf48fb682cb"
Path: /sitecore/templates/Project/Graybox/Pages/Homepage/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Network/16x16/home.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {A3BE331D-179B-4C7A-ABF8-522A293A2355}
    {7E111270-9CD0-4555-982B-E9BDDC32B798}
    {9FA3D41E-7CC0-4549-B0F1-B8683DF28E75}
    {EB9DA56D-99FE-4AEB-8919-97AE4B416DA7}
    {A45CFEAB-A8F8-4188-8973-40B090802A02}
    {E7BAAE0C-569F-4674-A9D3-D2521779A664}
    {C94896A0-D089-41DF-8533-F901666BB959}
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{F904F489-7129-4A77-8791-59662AB2B399}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{A2DE3965-E340-45B4-9FAB-3F35BECE08C1}">
        <p
          uid="{5605D0E9-BB08-4074-ADE5-7400F1C2092C}"
          key="content-body"
          md="{621E9296-0EFC-4B4F-86E5-F2DC23ED2B98}" />
        <p
          uid="{C70FD1C2-286D-425F-BE37-CD109EB74A83}"
          key="full-width-column"
          md="{ECD849AD-5A36-4FF4-829A-027BCD462E51}" />
        <p
          uid="{C0872714-1538-4446-8FA3-A7CC7B3F01F6}"
          key="content-width-column"
          md="{B773814E-2AB2-40E3-B3C3-F92972B23B11}" />
        <p
          uid="{65CC2417-6041-4A74-A126-C6D2BAE2D114}"
          key="50-50-left-column"
          md="{116F0349-80D2-4101-B1C5-F5B08EE8B3E8}" />
        <p
          uid="{876B6428-46A4-48C8-93CE-8CDD0A814233}"
          key="50-50-right-column"
          md="{116F0349-80D2-4101-B1C5-F5B08EE8B3E8}" />
        <r
          ds=""
          id="{1F3770B7-9F50-4F79-960E-081A0FCB7313}"
          par="Cascade=1"
          ph="content-header"
          uid="{1C184262-5CC1-41B3-A1F2-58178DB62456}" />
        <r
          id="{04E17BDE-B4F7-4B77-BED6-2A24F059D04D}"
          ph="content-body"
          uid="{D5F7149A-5382-4EAF-8802-97EE2AF67EA1}" />
        <r
          id="{60C2AC1C-4754-4914-B11A-37F0DF825B43}"
          ph="content-body"
          uid="{87C0F494-31A8-4458-9116-31CB8821205B}" />
        <r
          id="{3E615E7F-8DB2-4648-B7E1-E9C2F05FFD08}"
          ph="content-body"
          uid="{4CBF64C0-ED15-4AAC-844D-7500C7E4F62D}" />
        <r
          ds=""
          id="{028B4243-606E-4166-AAE9-C89499009F72}"
          par="Cascade=1"
          ph="content-footer"
          uid="{3283C774-4179-4357-B008-2BEE2954E1CC}" />
        <r
          id="{C12A4398-FA42-4DA5-B0D7-3E489664D45E}"
          ph="footer-scripts"
          uid="{DD365E46-101A-47B6-92F2-0185BEE1100A}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160222T142849Z
