---
ID: "97362531-cd2e-4638-aeda-e95db9ead113"
Parent: "0c887ab2-fb9c-42cd-bd93-b89041cf01fe"
Template: "0c887ab2-fb9c-42cd-bd93-b89041cf01fe"
Path: /sitecore/templates/Project/Graybox/Pages/Landing Page/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: People/16x16/cubes_green.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {EB9DA56D-99FE-4AEB-8919-97AE4B416DA7}
    {9FA3D41E-7CC0-4549-B0F1-B8683DF28E75}
    {6B719B44-AC8F-4A4E-984B-FC975C3F0749}
    {C94896A0-D089-41DF-8533-F901666BB959}
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{F904F489-7129-4A77-8791-59662AB2B399}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{A2DE3965-E340-45B4-9FAB-3F35BECE08C1}">
        <p
          uid="{F68BCE00-453D-46B5-BD0A-7B181E54AF7E}"
          key="content-width-column"
          md="/sitecore/layout/Placeholder Settings/Project/Graybox/Landing Page/Containers/Full Width Content" />
        <p
          uid="{80C131B0-31D5-4145-AD41-E7385A7EC3DF}"
          key="primary-column-left"
          md="/sitecore/layout/Placeholder Settings/Project/Graybox/Landing Page/Containers/70 Percent Left Column" />
        <p
          uid="{72E14C20-70CC-44A3-A51E-CB48CB819C69}"
          key="primary-column-right"
          md="/sitecore/layout/Placeholder Settings/Project/Graybox/Landing Page/Containers/70 Percent Right Column" />
        <r
          id="{04E17BDE-B4F7-4B77-BED6-2A24F059D04D}"
          ph="content-body"
          uid="{D38DF4A2-F2CA-4431-92A7-A93F417825AC}" />
        <r
          id="{6F3D1130-74EC-4C8B-B8A7-8BD1D51B17E7}"
          ph="content-body"
          uid="{45E04B4B-821E-4020-9C76-0CD6B4222B8B}" />
        <r
          id="{60C2AC1C-4754-4914-B11A-37F0DF825B43}"
          ph="content-body"
          uid="{DBED5F78-D869-4735-AC08-B3D22D40ABCA}" />
        <r
          id="{3E615E7F-8DB2-4648-B7E1-E9C2F05FFD08}"
          ph="content-body"
          uid="{F698CBCB-237C-408A-A509-70FEAE398851}" />
        <r
          id="{1B8B6412-BC11-4D18-8547-28380C1BCCF7}"
          ph="content-body"
          uid="{354C1B40-6C0B-44C4-94DB-BCB2B45A78E3}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160307T220338Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
